board.addPiece(new Pawn([0, 6], false))
board.addPiece(new Pawn([1, 6], false))
board.addPiece(new Pawn([2, 6], false))
board.addPiece(new Pawn([3, 6], false))
board.addPiece(new Pawn([4, 6], false))
board.addPiece(new Pawn([5, 6], false))
board.addPiece(new Pawn([6, 6], false))
board.addPiece(new Pawn([7, 6], false))

board.addPiece(new Pawn([0, 1], true))
board.addPiece(new Pawn([1, 1], true))
board.addPiece(new Pawn([2, 1], true))
board.addPiece(new Pawn([3, 1], true))
board.addPiece(new Pawn([4, 1], true))
board.addPiece(new Pawn([5, 1], true))
board.addPiece(new Pawn([6, 1], true))
board.addPiece(new Pawn([7, 1], true))

board.addPiece(new Rook([0, 0], true))
board.addPiece(new Rook([7, 0], true))
board.addPiece(new Rook([0, 7], false))
board.addPiece(new Rook([7, 7], false))

board.addPiece(new Knight([1, 0], true))
board.addPiece(new Knight([6, 0], true))
board.addPiece(new Knight([1, 7], false))
board.addPiece(new Knight([6, 7], false))

board.addPiece(new Bishop([2, 0], true))
board.addPiece(new Bishop([5, 0], true))
board.addPiece(new Bishop([2, 7], false))
board.addPiece(new Bishop([5, 7], false))

board.addPiece(new Queen([3, 0], true))
board.addPiece(new Queen([3, 7], false))

board.addPiece(new King([4, 0], true))
board.addPiece(new King([4, 7], false))